// User Type và danh sách chức năng theo UC8 (bước 3: "Feature availability reflects the user type").
export const USER_TYPES = Object.freeze({
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
})

export const FEATURES = Object.freeze({
  EDIT_PLACE_INFO: 'EDIT_PLACE_INFO',
  MANAGE_AUDIO: 'MANAGE_AUDIO',
  LISTEN_MANAGEMENT: 'LISTEN_MANAGEMENT',
  MANAGER_ACCOUNT_MANAGEMENT: 'MANAGER_ACCOUNT_MANAGEMENT',
  PLACES_MANAGEMENT: 'PLACES_MANAGEMENT',
  MAP_MANAGEMENT: 'MAP_MANAGEMENT',
  BUS_LINE_MANAGEMENT: 'BUS_LINE_MANAGEMENT',
  LOG_OFF: 'LOG_OFF',
})

export const FEATURES_BY_USER_TYPE = Object.freeze({
  [USER_TYPES.MANAGER]: [
    FEATURES.EDIT_PLACE_INFO,
    FEATURES.MANAGE_AUDIO,
    FEATURES.LOG_OFF,
  ],
  [USER_TYPES.ADMIN]: [
    FEATURES.LISTEN_MANAGEMENT,
    FEATURES.MANAGER_ACCOUNT_MANAGEMENT,
    FEATURES.PLACES_MANAGEMENT,
    FEATURES.MAP_MANAGEMENT,
    FEATURES.BUS_LINE_MANAGEMENT,
    FEATURES.LOG_OFF,
  ],
})

export function getFeaturesForUserType(userType) {
  return FEATURES_BY_USER_TYPE[userType] ?? []
}
